version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=development
      - MYSQL_DATABASE=test_db
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./src/main/resources/schemas/create2.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"